name: marketing_banner_sdui
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  stac: ^0.10.0
  stac_framework: ^0.2.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
